name = "NDHistograms"
uuid = "c9719566-2c26-451b-95bc-5aa9e2747dfa"
authors = ["josePereiro <jose.pereiro.personal@gmail.com> and contributors"]
version = "1.1.3"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
